# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/user/UnrealEngine
GAMEPROJECTFILE =/home/user/Documents/Unreal Projects/TakeoffSendario/TakeoffSendario.uproject

TARGETS = \
	TakeoffSendario-Linux-DebugGame  \
	TakeoffSendario-Linux-Shipping  \
	TakeoffSendario \
	TakeoffSendarioEditor-Linux-DebugGame  \
	TakeoffSendarioEditor-Linux-Shipping  \
	TakeoffSendarioEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TakeoffSendarioEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TakeoffSendarioEditor-Linux-Debug


TakeoffSendario-Linux-DebugGame:
	 $(PROJECTBUILD) TakeoffSendario Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TakeoffSendario-Linux-Shipping:
	 $(PROJECTBUILD) TakeoffSendario Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TakeoffSendario:
	 $(PROJECTBUILD) TakeoffSendario Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TakeoffSendarioEditor-Linux-DebugGame:
	 $(PROJECTBUILD) TakeoffSendarioEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TakeoffSendarioEditor-Linux-Shipping:
	 $(PROJECTBUILD) TakeoffSendarioEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TakeoffSendarioEditor:
	 $(PROJECTBUILD) TakeoffSendarioEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
